### PR TITLE
WIP: Dockerize Act with Plack

### PR DESCRIPTION
**Pull request by waterkip**
Hello,

I was asked to Dockerize Act in order to make it easier to develop on a box and to make use of the psgi branch. I've done some work in the past two weekends to get Act to work with Docker and Plack. This is the stil WIP version of that branch (the commits are a bit messy).

This branch is based upon `book/master` and has `book/psgi` and `ichesnokov/psgi_fixes` in it by virtue of a rebase.

I would love to get some feedback on this and maybe some tests as I don't have a database which represents the real world. If you want to have a go at it, the setup is explained in the README.md and should be straight forward as long as you have Docker and Docker Compose installed. I've tested it with some conferences found over at the [Act-Conference](https://github.com/Act-Conferences) and it seems to work.

### CODE REVIEW

**Comment by HaraldJoerg** [comment]
A question: How do I run the tests or do debugging in that setup?  After all is said and done, I get a "database version 0 is too old" message in the Plack stacktrace for http://localhost:5000/.  This is clearly a message from Act, it which usually indicates an error in connecting to the database.  I _can_ connect with psql.  I am running on a fresh Virtualbox VM under Debian buster and an up-to-date docker from their repository, if that matters.

**Comment by waterkip** [comment]
Set `version_check = 0` in the db section in your act.ini

**Comment by book** [comment]
Regarding the database version, the script `bin/dbupdate` is meant to update your current schema to the latest.

**Comment by waterkip** [comment]
I know, but I did not want to install Act on the DB server just for the script to work.

**Comment by vanHoesel** [comment]
You probably wouldn't had to if you had run `bin/dbinit` and `bin/dbupdate` with the correct settings on an empty DB server. Those would have build your databases. If I Remember Correctly

**Comment by waterkip** [comment]
That would require actions directly after setting up docker, now the DB takes care of that itself. You can always recreate the DB itself from the Act container if you have that up and running. But that will remove the demo user. Unless we add the demo user to the `bin/dbinit`.

I was thinking along the lines of using the `db/act/template.sql` file in `dbinit` so we don't duplicate code. But.. I don't think I see a use for `dbinit` in a Dockerized environment. You can now just `docker-compose rm -s -f act-db` and `docker volume rm act_act_db`, `docker up` and are good to go.

You can always insert the version, you can do that by added a file in `db/act/initial/03_version.sql` which sets the version (and then remember to bump that after a DB upgrade). It would probably require some modifications to `bin/dbupdate` to also regenerate this SQL file if found.

**Comment by waterkip** [comment]
Since this PR has been open for a pretty long time, I'm going to close it.

**Pull request closed without merging**
